In [88]:
import pandas as pd

In [89]:
dataset = pd.read_csv("Medical Dataset/Training.csv")
dataset.head()
#dataset.info()
#dataset.shape

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [90]:
dataset['prognosis'].unique()
#len(dataset['prognosis'].unique())
#dataset.isna().sum()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [91]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [92]:
encoder = LabelEncoder()
dataset['prognosis'] = encoder.fit_transform(dataset['prognosis'])
dataset['prognosis']

0       15
1       15
2       15
3       15
4       15
        ..
4915     0
4916     2
4917    38
4918    35
4919    27
Name: prognosis, Length: 4920, dtype: int32

In [93]:
x = dataset.drop('prognosis', axis = 1)
y = dataset['prognosis']
x
#y

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
0     ...                   0           0         0             0   
1     ...                   0           0         0             0   
2     ...                   0           0         0             0   
3     ...                   0           0         0             0   
4     ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
4915  ...                   0           0         0             0   
4916  ...                   1           1         1             0   
4917  ...                   0           0         0             0   
4918  ...                   0           0         0             1   
4919  ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
0                       0                     0                   0        0   
1                       0                     0                   0        0   
2                       0                     0                   0        0   
3                       0                     0                   0        0   
4                       0                     0                   0        0   
...                   ...                   ...                 ...      ...   
4915                    0                     0                   0        0   
4916                    0                     0                   0        0   
4917                    0                     0                   0        0   
4918                    1                     1                   1        0   
4919                    0                     0                   0        1   

      red_sore_around_nose  yellow_crust_ooze  
0                        0                  0  
1                        0                  0  
2                        0                  0  
3                        0                  0  
4                        0                  0  
...                    ...                ...  
4915                     0                  0  
4916              

In [94]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state = 42)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((3936, 132), (984, 132), (3936,), (984,))

In [95]:
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np

In [96]:
models = {
    'SVC' : SVC(kernel='linear'),
    'RandomForestClassifier' : RandomForestClassifier(n_estimators=100, random_state=42),
    'GradientBoosting' : GradientBoostingClassifier(n_estimators=100, random_state=42),
    'KNeighbors' : KNeighborsClassifier(n_neighbors=5),
    'MultinomialNB' : MultinomialNB()
}

for model_name, model in models.items():
    #print(model_name, ':', model)

    #train model
    model.fit(x_train,y_train)
    #predict_model
    predictions = model.predict(x_test)
    #calculate_accuracy
    accuracy = accuracy_score(y_test,predictions)
    #confusion_matrix
    cm = confusion_matrix(y_test, predictions)
    #display
    print(f'{model_name} Accuracy : {accuracy}')
    print('\n')
    print(f'{model_name} Confusion_Matrix :')
    print(cm)
    print('\n')

SVC Accuracy : 1.0


SVC Confusion_Matrix :
[[18  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  0 24 ...  0  0  0]
 ...
 [ 0  0  0 ... 26  0  0]
 [ 0  0  0 ...  0 22  0]
 [ 0  0  0 ...  0  0 34]]


RandomForestClassifier Accuracy : 1.0


RandomForestClassifier Confusion_Matrix :
[[18  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  0 24 ...  0  0  0]
 ...
 [ 0  0  0 ... 26  0  0]
 [ 0  0  0 ...  0 22  0]
 [ 0  0  0 ...  0  0 34]]


GradientBoosting Accuracy : 1.0


GradientBoosting Confusion_Matrix :
[[18  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  0 24 ...  0  0  0]
 ...
 [ 0  0  0 ... 26  0  0]
 [ 0  0  0 ...  0 22  0]
 [ 0  0  0 ...  0  0 34]]


KNeighbors Accuracy : 1.0


KNeighbors Confusion_Matrix :
[[18  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  0 24 ...  0  0  0]
 ...
 [ 0  0  0 ... 26  0  0]
 [ 0  0  0 ...  0 22  0]
 [ 0  0  0 ...  0  0 34]]


MultinomialNB Accuracy : 1.0


MultinomialNB Confusion_Matrix :
[[18  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]


In [97]:
svc = SVC(kernel='linear')
svc.fit(x_train, y_train)
ypred = svc.predict(x_test)
accuracy_score(y_test, ypred)

1.0

In [98]:
##saving model
import pickle
pickle.dump(svc, open("Model/svc.pkl",'wb'))

#load model
svc = pickle.load(open("Model/svc.pkl",'rb'))

In [99]:
# Prediction 1
print('Predicted Label:', svc.predict(x_test.iloc[[0]])[0])
print('Actual Label:', y_test.iloc[0])
print('\n')
# Prediction 2
print('Predicted Label:', svc.predict(x_test.iloc[[25]])[0])
print('Actual Label:', y_test.iloc[25])

Predicted Label: 2
Actual Label: 2


Predicted Label: 20
Actual Label: 20


In [100]:
sym_des = pd.read_csv('Medical Dataset/symtoms_df.csv')
precautions = pd.read_csv('Medical Dataset/precautions_df.csv')
workout = pd.read_csv('Medical Dataset/workout_df.csv')
description = pd.read_csv('Medical Dataset/description.csv')
medications = pd.read_csv('Medical Dataset/medications.csv')
diets = pd.read_csv('Medical Dataset/diets.csv')
sym_des.head()
#precautions.head()
#workout.head()
#description.head()
#medication.head()
#diets.head()

Unnamed: 0           Disease   Symptom_1              Symptom_2  \
0           0  Fungal infection     itching              skin_rash   
1           1  Fungal infection   skin_rash   nodal_skin_eruptions   
2           2  Fungal infection     itching   nodal_skin_eruptions   
3           3  Fungal infection     itching              skin_rash   
4           4  Fungal infection     itching              skin_rash   

               Symptom_3             Symptom_4  
0   nodal_skin_eruptions   dischromic _patches  
1    dischromic _patches                   NaN  
2    dischromic _patches                   NaN  
3    dischromic _patches                   NaN  
4   nodal_skin_eruptions                   NaN

In [104]:
import numpy as np
import warnings
warnings.filterwarnings("ignore", category=UserWarning)
def helper(dis):
    desc = " ".join(description.loc[description['Disease'] == dis, 'Description'].values)

    pre = precautions.loc[precautions['Disease'] == dis, ['Precaution_1', 'Precaution_2', 'Precaution_3', 'Precaution_4']].values.flatten().tolist()
    med = medications.loc[medications['Disease'] == dis, 'Medication'].values.tolist()
    die = diets.loc[diets['Disease'] == dis, 'Diet'].values.tolist()
    wrkout = workout.loc[workout['disease'] == dis, 'workout'].values.tolist()

    return desc, pre, med, die, wrkout


def get_predicted_value(patient_symptoms):
    input_vector = np.zeros(len(symptoms_dict))
    for item in patient_symptoms:
        if item in symptoms_dict:   # safeguard
            input_vector[symptoms_dict[item]] = 1
    return diseases_list[svc.predict([input_vector])[0]]


# ---- MAIN LOGIC ----
symptoms = input("Enter your symptoms (comma-separated): ")
user_symptoms = [s.strip("[]' ") for s in symptoms.split(',')]

predicted_disease = get_predicted_value(user_symptoms)
desc, pre, med, die, wrkout = helper(predicted_disease)

print("\n=== Predicted Disease ===")
print(predicted_disease)

sections = {
    "Description": [desc],
    "Precautions": pre,
    "Medications": med,
    "Workout": wrkout,
    "Diets": die
}

for title, items in sections.items():
    print(f"\n=== {title} ===")
    for i, val in enumerate(items, 1):
        print(f"{i}: {val}")

Enter your symptoms (comma-separated):  itching, skin_rash, nodal_eruption



=== Predicted Disease ===
Fungal infection

=== Description ===
1: Fungal infection is a common skin condition caused by fungi.

=== Precautions ===
1: bath twice
2: use detol or neem in bathing water
3: keep infected area dry
4: use clean cloths

=== Medications ===
1: ['Antifungal Cream', 'Fluconazole', 'Terbinafine', 'Clotrimazole', 'Ketoconazole']

=== Workout ===
1: Avoid sugary foods
2: Consume probiotics
3: Increase intake of garlic
4: Include yogurt in diet
5: Limit processed foods
6: Stay hydrated
7: Consume green tea
8: Eat foods rich in zinc
9: Include turmeric in diet
10: Eat fruits and vegetables

=== Diets ===
1: ['Antifungal Diet', 'Probiotics', 'Garlic', 'Coconut oil', 'Turmeric']
